#!/usr/bin/env bash
# ══════════════════════════════════════════════════════════════════════════════
# CyberSentinel SOAR v3.0 — Server Deployment Script
# ══════════════════════════════════════════════════════════════════════════════
# Deploy on any server with external IP access.
# Builds from source (for dev/staging). For production GHCR deployments,
# use cybersentinel-deploy-soar.sh instead.
#
# Usage:
#   chmod +x deploy-server.sh
#   ./deploy-server.sh
# ══════════════════════════════════════════════════════════════════════════════

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

log_info()  { echo -e "${CYAN}[INFO]${NC}  $1"; }
log_ok()    { echo -e "${GREEN}[  OK]${NC}  $1"; }
log_warn()  { echo -e "${YELLOW}[WARN]${NC}  $1"; }
log_fail()  { echo -e "${RED}[FAIL]${NC}  $1"; }
fail_exit() { log_fail "$1"; exit 1; }

separator() {
    echo -e "${BOLD}──────────────────────────────────────────────────────────────${NC}"
}

echo -e "${BOLD}╔═══════════════════════════════════════════════════════════╗${NC}"
echo -e "${BOLD}║     CyberSentinel SOAR v3.0 — Server Deployment         ║${NC}"
echo -e "${BOLD}╚═══════════════════════════════════════════════════════════╝${NC}"
echo ""

# ── Step 1: Detect network ───────────────────────────────────────────────────

separator
log_info "Step 1/6 — Detecting network"

PRIMARY_IP=$(hostname -I 2>/dev/null | awk '{print $1}' || echo "unknown")
PUBLIC_IP=$(curl -s -4 --connect-timeout 5 icanhazip.com 2>/dev/null || echo "")

echo "  Primary IP: ${PRIMARY_IP}"
[ -n "$PUBLIC_IP" ] && echo "  Public IP:  ${PUBLIC_IP}"

# ── Step 2: Prerequisites ───────────────────────────────────────────────────

separator
log_info "Step 2/6 — Checking prerequisites"

command -v docker &>/dev/null || fail_exit "Docker is not installed. Install: https://docs.docker.com/engine/install/"
docker info &>/dev/null || fail_exit "Docker daemon is not running. Start: sudo systemctl start docker"
log_ok "Docker: $(docker --version)"

if docker compose version &>/dev/null 2>&1; then
    COMPOSE_CMD="docker compose"
    log_ok "Docker Compose v2"
elif command -v docker-compose &>/dev/null; then
    COMPOSE_CMD="docker-compose"
    log_ok "Docker Compose v1: $(docker-compose --version)"
else
    fail_exit "Docker Compose not installed. Install: https://docs.docker.com/compose/install/"
fi

# ── Step 3: Firewall ─────────────────────────────────────────────────────────

separator
log_info "Step 3/6 — Firewall configuration"

read -rp "Configure firewall rules for ports 3000, 3001? (y/n): " FW_CHOICE
if [[ "${FW_CHOICE}" =~ ^[Yy]$ ]]; then
    if command -v ufw &>/dev/null; then
        sudo ufw allow 3000/tcp comment 'CyberSentinel Frontend' 2>/dev/null || true
        sudo ufw allow 3001/tcp comment 'CyberSentinel Backend API' 2>/dev/null || true
        log_ok "UFW rules added for ports 3000, 3001"
    elif command -v firewall-cmd &>/dev/null; then
        sudo firewall-cmd --permanent --add-port=3000/tcp 2>/dev/null || true
        sudo firewall-cmd --permanent --add-port=3001/tcp 2>/dev/null || true
        sudo firewall-cmd --reload 2>/dev/null || true
        log_ok "firewalld rules added for ports 3000, 3001"
    else
        log_warn "No firewall detected (ufw/firewalld). Manually open ports 3000, 3001 if needed."
    fi
else
    log_info "Skipping firewall configuration"
fi

# ── Step 4: Environment ──────────────────────────────────────────────────────

separator
log_info "Step 4/6 — Setting up environment"

if [ ! -f backend/.env ]; then
    log_warn "No backend/.env found — generating defaults..."

    JWT_SECRET=$(openssl rand -hex 32 2>/dev/null || head -c 64 /dev/urandom | od -An -tx1 | tr -d ' \n')
    SOAR_API_KEY=$(openssl rand -hex 16 2>/dev/null || head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n')

    CORS_ORIGINS="http://localhost:3000"
    [ -n "$PRIMARY_IP" ] && [ "$PRIMARY_IP" != "unknown" ] && CORS_ORIGINS="${CORS_ORIGINS},http://${PRIMARY_IP}:3000"

    cat > backend/.env << ENVEOF
# CyberSentinel SOAR v3.0 — Backend Environment
# Auto-generated by deploy-server.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

JWT_SECRET=${JWT_SECRET}
JWT_EXPIRES_IN=24h
SOAR_API_KEY=${SOAR_API_KEY}
PORT=3001
NODE_ENV=production

MONGODB_URI=mongodb://soar-database:27017
MONGODB_DB_NAME=cybersentinel

CORS_ORIGIN=${CORS_ORIGINS}

# Connector API keys (fill in to enable)
VIRUSTOTAL_API_KEY=
ABUSEIPDB_API_KEY=
ALIENVAULT_OTX_API_KEY=

# Notification integrations
SLACK_WEBHOOK_URL=
SMTP_HOST=
SMTP_PORT=587
SMTP_USER=
SMTP_PASS=

# CyberSentinel Control Plane API (for active response)
CYBERSENTINEL_CONTROL_PLANE_URL=
CYBERSENTINEL_CONTROL_PLANE_USER=
CYBERSENTINEL_CONTROL_PLANE_PASSWORD=

ENABLE_ALERT_STORAGE=false
ENABLE_LEGACY_PULL_INGESTION=false
ENVEOF

    log_ok "Created backend/.env with auto-generated secrets"
    log_warn "Edit backend/.env to add connector API keys before going to production"
else
    log_ok "backend/.env exists"
fi

# ── Step 5: Deploy ────────────────────────────────────────────────────────────

separator
log_info "Step 5/6 — Deploying CyberSentinel SOAR"

echo ""
echo -e "${YELLOW}This will:${NC}"
echo "  - Stop any existing CyberSentinel containers"
echo "  - Build Docker images from source"
echo "  - Start all services (MongoDB, Backend, Frontend)"
echo ""
read -rp "Continue with deployment? (y/n): " DEPLOY_CHOICE
if [[ ! "${DEPLOY_CHOICE}" =~ ^[Yy]$ ]]; then
    echo "Deployment cancelled."
    exit 0
fi

# Stop existing containers
if docker ps --format '{{.Names}}' | grep -q "^soar-"; then
    log_info "Stopping existing containers..."
    ${COMPOSE_CMD} down --remove-orphans 2>/dev/null || true
fi

log_info "Building Docker images..."
${COMPOSE_CMD} build --no-cache

log_info "Starting services..."
${COMPOSE_CMD} up -d

# ── Step 6: Verify ────────────────────────────────────────────────────────────

separator
log_info "Step 6/6 — Verifying deployment"

MAX_WAIT=90
ELAPSED=0

while [ $ELAPSED -lt $MAX_WAIT ]; do
    DB_HEALTH=$(docker inspect --format='{{.State.Health.Status}}' soar-database 2>/dev/null || echo "starting")
    BE_HEALTH=$(docker inspect --format='{{.State.Health.Status}}' soar-backend 2>/dev/null || echo "starting")
    FE_HEALTH=$(docker inspect --format='{{.State.Health.Status}}' soar-frontend 2>/dev/null || echo "starting")

    if [ "$DB_HEALTH" = "healthy" ] && [ "$BE_HEALTH" = "healthy" ] && [ "$FE_HEALTH" = "healthy" ]; then
        break
    fi

    echo -ne "\r  DB=${DB_HEALTH} | Backend=${BE_HEALTH} | Frontend=${FE_HEALTH} (${ELAPSED}s/${MAX_WAIT}s)  "
    sleep 5
    ELAPSED=$((ELAPSED + 5))
done

echo ""
echo ""

# Test endpoints
FRONTEND_OK=false
BACKEND_OK=false

curl -sf http://localhost:3000 > /dev/null 2>&1 && FRONTEND_OK=true
curl -sf http://localhost:3001/health > /dev/null 2>&1 && BACKEND_OK=true

$FRONTEND_OK && log_ok "Frontend: accessible" || log_warn "Frontend: not responding"
$BACKEND_OK && log_ok "Backend: healthy" || log_warn "Backend: not responding"

# ── Summary ───────────────────────────────────────────────────────────────────

echo ""
echo -e "${GREEN}${BOLD}╔═══════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}${BOLD}║  CyberSentinel SOAR v3.0 — Deployment Complete           ║${NC}"
echo -e "${GREEN}${BOLD}╚═══════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "${BOLD}Access URLs:${NC}"
echo -e "  Local:    http://localhost:3000"
echo -e "  Network:  http://${PRIMARY_IP}:3000"
[ -n "$PUBLIC_IP" ] && echo -e "  Public:   http://${PUBLIC_IP}:3000"
echo ""
echo -e "${BOLD}Default login:${NC} soaradmin / CyberSentinelSOAR@2026"
echo ""
echo -e "${BOLD}Commands:${NC}"
echo "  Logs:     ${COMPOSE_CMD} logs -f"
echo "  Stop:     ${COMPOSE_CMD} down"
echo "  Restart:  ${COMPOSE_CMD} restart"
echo "  Status:   ${COMPOSE_CMD} ps"
echo ""
