#!/usr/bin/env bash
# ══════════════════════════════════════════════════════════════════════════════
# CyberSentinel SOAR v3.0 — Quick Start Script
# ══════════════════════════════════════════════════════════════════════════════
# Builds and starts all services locally using Docker Compose.
# For production deployments pulling from GHCR, use cybersentinel-deploy-soar.sh
#
# Usage:
#   chmod +x start.sh
#   ./start.sh
# ══════════════════════════════════════════════════════════════════════════════

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

echo -e "${BOLD}╔═══════════════════════════════════════════════════════════╗${NC}"
echo -e "${BOLD}║     CyberSentinel SOAR v3.0 — Quick Start               ║${NC}"
echo -e "${BOLD}╚═══════════════════════════════════════════════════════════╝${NC}"
echo ""

# ── Pre-flight checks ────────────────────────────────────────────────────────

# Check Docker
if ! docker info > /dev/null 2>&1; then
    echo -e "${RED}Docker is not running. Please start Docker and try again.${NC}"
    exit 1
fi
echo -e "${GREEN}[OK]${NC} Docker is running"

# Check Docker Compose
if docker compose version &>/dev/null 2>&1; then
    COMPOSE_CMD="docker compose"
elif command -v docker-compose &>/dev/null; then
    COMPOSE_CMD="docker-compose"
else
    echo -e "${RED}Docker Compose is not installed.${NC}"
    echo "Install: https://docs.docker.com/compose/install/"
    exit 1
fi
echo -e "${GREEN}[OK]${NC} Docker Compose available"

# ── Backend .env ──────────────────────────────────────────────────────────────

if [ ! -f backend/.env ]; then
    echo -e "${YELLOW}[WARN]${NC} backend/.env not found — generating defaults..."

    JWT_SECRET=$(openssl rand -hex 32 2>/dev/null || head -c 64 /dev/urandom | od -An -tx1 | tr -d ' \n')
    SOAR_API_KEY=$(openssl rand -hex 16 2>/dev/null || head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n')

    cat > backend/.env << ENVEOF
# CyberSentinel SOAR v3.0 — Backend Environment
# Auto-generated by start.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

JWT_SECRET=${JWT_SECRET}
JWT_EXPIRES_IN=24h
SOAR_API_KEY=${SOAR_API_KEY}
PORT=3001
NODE_ENV=production

MONGODB_URI=mongodb://soar-database:27017
MONGODB_DB_NAME=cybersentinel

CORS_ORIGIN=http://localhost:3000

# Connector API keys (optional — fill in to enable enrichment)
VIRUSTOTAL_API_KEY=
ABUSEIPDB_API_KEY=
ALIENVAULT_OTX_API_KEY=

# Notification integrations (optional)
SLACK_WEBHOOK_URL=
SMTP_HOST=
SMTP_PORT=587
SMTP_USER=
SMTP_PASS=

ENABLE_ALERT_STORAGE=false
ENABLE_LEGACY_PULL_INGESTION=false
ENVEOF

    echo -e "${GREEN}[OK]${NC} Created backend/.env with auto-generated secrets"
    echo -e "${YELLOW}     Edit backend/.env to add connector API keys (VirusTotal, etc.)${NC}"
else
    echo -e "${GREEN}[OK]${NC} backend/.env exists"
fi

# ── Build & Start ─────────────────────────────────────────────────────────────

echo ""
echo -e "${CYAN}Building Docker images...${NC}"
${COMPOSE_CMD} build

echo ""
echo -e "${CYAN}Starting services...${NC}"
${COMPOSE_CMD} up -d

# ── Health check ──────────────────────────────────────────────────────────────

echo ""
echo -e "${CYAN}Waiting for services to become healthy...${NC}"

MAX_WAIT=90
ELAPSED=0

while [ $ELAPSED -lt $MAX_WAIT ]; do
    DB_HEALTH=$(docker inspect --format='{{.State.Health.Status}}' soar-database 2>/dev/null || echo "starting")
    BE_HEALTH=$(docker inspect --format='{{.State.Health.Status}}' soar-backend 2>/dev/null || echo "starting")
    FE_HEALTH=$(docker inspect --format='{{.State.Health.Status}}' soar-frontend 2>/dev/null || echo "starting")

    if [ "$DB_HEALTH" = "healthy" ] && [ "$BE_HEALTH" = "healthy" ] && [ "$FE_HEALTH" = "healthy" ]; then
        break
    fi

    echo -ne "\r  DB=${DB_HEALTH} | Backend=${BE_HEALTH} | Frontend=${FE_HEALTH} (${ELAPSED}s/${MAX_WAIT}s)  "
    sleep 5
    ELAPSED=$((ELAPSED + 5))
done

echo ""

SERVER_IP=$(hostname -I 2>/dev/null | awk '{print $1}' || echo "localhost")

if [ "$DB_HEALTH" = "healthy" ] && [ "$BE_HEALTH" = "healthy" ] && [ "$FE_HEALTH" = "healthy" ]; then
    echo ""
    echo -e "${GREEN}${BOLD}╔═══════════════════════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}${BOLD}║  CyberSentinel SOAR v3.0 is running!                      ║${NC}"
    echo -e "${GREEN}${BOLD}╚═══════════════════════════════════════════════════════════╝${NC}"
    echo ""
    echo -e "  Frontend  → ${CYAN}http://${SERVER_IP}:3000${NC}"
    echo -e "  Backend   → ${CYAN}http://${SERVER_IP}:3001${NC}"
    echo -e "  Health    → ${CYAN}http://${SERVER_IP}:3001/health${NC}"
    echo ""
    echo -e "  Default login: ${BOLD}soaradmin${NC} / ${BOLD}CyberSentinelSOAR@2026${NC}"
    echo ""
    echo -e "  Logs   → ${YELLOW}${COMPOSE_CMD} logs -f${NC}"
    echo -e "  Stop   → ${YELLOW}${COMPOSE_CMD} down${NC}"
    echo ""
else
    echo -e "${RED}Not all services are healthy after ${MAX_WAIT}s.${NC}"
    echo -e "Check logs: ${COMPOSE_CMD} logs"
fi
